### ISSUE TITLE
VMware创建AZ时，默认模板导入失败

### ISSUE THREAD

**Issue by andyguo1985** [KubeOperator/KubeOperator#282]
**请描述您的需求或者改进建议.**
VMware 云平台创建AZ时，导入默认模板失败了，但AZ状态依旧显示就绪状态，且没有任何告警提示。

**请描述你建议的实现方案**
如果模板导入任务执行异常，在系统日志中进行显著提示。

**Comment by lvxiaohu** [comment]
请提供问题截图，以及你的环境的详细信息。

**Comment by Leon092188** [comment]
名称:cloud_provider
级别:ERROR
文件名:models.py
方法名:create_image
行号:133
消息:upload os image error!
主机IP:172.18.0.3
时间:2020-05-27 21:01:28
堆栈信息:
Traceback (most recent call last):
  File "/opt/kubeOperator-api/apps/cloud_provider/models.py", line 130, in create_image
    client.create_image(zone=self)
  File "/opt/kubeOperator-api/apps/cloud_provider/clients/vsphere.py", line 143, in create_image
    spec_params)
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 511, in _InvokeMethod
    list(map(CheckField, info.params, args))
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 1041, in CheckField
    raise TypeError('Required field "%s" not provided (not @optional)' % info.name)
TypeError: Required field "ovfDescriptor" not provided (not @optional)

**Comment by Leon092188** [comment]
请问这是个什么问题？主机IP我自己配置的是10.2.19.16。这边显示的怎么是主机IP:172.18.0.3？ 谢谢！

**Comment by lvxiaohu** [comment]
请确定 KubeOperator 管理控制台中，系统设置-系统-本级IP 是否配置正确，这个是你 KubeOperator 部署机的IP。
