### ISSUE TITLE
Vsphere 创建AZ错误

### ISSUE THREAD

**Issue by Leon092188** [KubeOperator/KubeOperator#284]
名称:cloud_provider
级别:ERROR
文件名:models.py
方法名:create_image
行号:133
消息:upload os image error!
主机IP:172.18.0.3
时间:2020-05-27 21:01:28
堆栈信息:
Traceback (most recent call last):
File "/opt/kubeOperator-api/apps/cloud_provider/models.py", line 130, in create_image
client.create_image(zone=self)
File "/opt/kubeOperator-api/apps/cloud_provider/clients/vsphere.py", line 143, in create_image
spec_params)
File "/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 706, in
self.f(*(self.args + (obj,) + args), **kwargs)
File "/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 511, in _InvokeMethod
list(map(CheckField, info.params, args))
File "/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 1041, in CheckField
raise TypeError('Required field "%s" not provided (not @optional)' % info.name)
TypeError: Required field "ovfDescriptor" not provided (not @optional)

**Comment by lvxiaohu** [comment]
1. 请确定绑定的 vsphere 是否有上传权限。可以去手动模拟上传文件。
2. 系统管理-设置-本机IP填写正确 （KubeOperator 的IP ）

**Comment by Leon092188** [comment]
你好！
1.确定是有上传权限的
2.IP也确定是对的

**Comment by lvxiaohu** [comment]
你使用的是 KubeOperator 提供的默认模板，还是你自己的模板呢？

**Comment by Leon092188** [comment]
默认模板和自定义的模板都不行。都是报这个错

**Comment by lvxiaohu** [comment]
默认模板在部分 vSphere 环境中可能会出现参数不匹配问题，建议先使用自定义模板。 你可以先使用自定义模板去创建机器，看看是否能够成功，之后再使用 KubeOperator 去创建。如果遇到错误，请贴出详细错误日志。
