### ISSUE TITLE
无法选择离线包

### ISSUE THREAD

**Issue by linandli** [KubeOperator/KubeOperator#292]
**KubeOperator 版本**
2.6.18

**Bug 描述**
无法选择离线包

**Bug 重现步骤**
1. 点击创建集群 
2. 选择离线包

**期待的正确结果**
正常选择

**Comment by wanghe-fit2cloud** [comment]
1、kubeoperator部署机执行docker ps -a | grep nexus，确定离线包容器运行状态是否Up
2、离线包菜单点击刷新按钮，确定离线包状态是否在线

**Comment by linandli** [comment]
1a95bcb8620a        registry.fit2cloud.com/public/nexus-helm:3.15.2-01   "sh -c ${SONATYPE_..."   5 minutes ago       Exited (255) 37 seconds ago                         v1-16-9


页面点击离线包，可以查看到：kubernetes-1.16.9

**Comment by wanghe-fit2cloud** [comment]
离线包容器状态 Exited，看下容器log，确定下具体原因

**Comment by tangjia-ln** [comment]
OpenJDK 64-Bit Server VM warning: Cannot open file ../sonatype-work/nexus3/log/jvm.log due to Permission denied
Warning:  Cannot open log file: ../sonatype-work/nexus3/log/jvm.log
Warning:  Forcing option -XX:LogFile=/tmp/jvm.log
Unable to delete file: /nexus-data/cache/bundle267/version0.0/revision.location
Unable to update instance pid: /nexus-data/instances/instance.properties (Permission denied)
Exception in thread "Thread-2" java.lang.SecurityException: Could not lock User prefs. Lock file access denied.
	at java.util.prefs.FileSystemPreferences.checkLockFile0ErrorCode(FileSystemPreferences.java:937)
	at java.util.prefs.FileSystemPreferences.lockFile(FileSystemPreferences.java:925)
	at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:729)
	at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
	at java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:464)
	at java.util.prefs.FileSystemPreferences.access$1200(FileSystemPreferences.java:50)
	at java.util.prefs.FileSystemPreferences$4$1.run(FileSystemPreferences.java:442)

**Comment by tangjia-ln** [comment]
我也遇到了同样的问题，相同的版本在公有云上是正常的，在私有云openstack的kvm上就一直nexus起不来。我发现nexus不是在docker-compose中编排的，而是写在代码里，package的model里，但追着追着就断了，不知道为什么这么设计，不把nexus也放到docker-compose里

**Comment by wanghe-fit2cloud** [comment]
每个离线包容器对应的是一个k8s版本，在kubeoperator部署机上会根据用户需要出现不同数量的离线包容器。

Cannot open file ../sonatype-work/nexus3/log/jvm.log due to Permission denied 这是错误原因。
